parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:react/recommended
env:
  browser: true
  jest: true
rules:
  no-console: off
  react/prop-types: off
  react/display-name: off
globals:
  process: false
